[package]
name = "lecturecut"
version = "0.1.0"

[dependencies]
argparse = "0.2.2"
console = "0.15.5"
indicatif = "0.17.3"
libloading = "0.8.0"
tree_magic = "0.2.3"
once_cell = "1.17.1"
ellipse = "0.2.0"

[dependencies.tabled]
version = "0.12.0"
features = ["color"]
